import {NativeScene} from './native-scene.js';
import {escapeXML as esc,format,heatmap,torqueBars,responseChart,chartCSV,downloadFile,downloadPNG,sameChannels,frameAtTime,validFrame} from './charts.js';
import {effectiveRequest,matchingExperiment,parameterValues,inspectorSummary,validatePreset,verifyNativeBinding} from './contracts.js';
import {createRequestEditor} from './request-editor.js';
import {comparisonManifest,matchingRequestedParameters,sensitivityData,sensitivityChart,sensitivityCSV} from './comparison.js';
import {PARAMETER_HELP,parameterHelpHTML} from './parameter-help.js';
import {jointBalanceChart} from './balance-chart.js';

const DATA='./explainer/native-v2/data/';
const LESSON=[
 ['发指令','给肌肉一个用力指令。','动作指令 → 控制 ctrl','先选一组原生记录，播放短指令；控制不是激活，也不是肌力。'],
 ['肌肉响应','激活随时间变化，肌肉产生拉力。','控制＋当前姿态与速度 → 激活与拉力','激活有滞后；相同激活下，长度和速度不同，产力也可能不同。'],
 ['拉动关节','拉力通过肌腱路径作用到关节。','肌力＋路径力臂 → 关节力矩','选一个关节，看所有肌肉各贡献多少力矩；正负表示作用方向。'],
 ['手动起来','合力决定下一刻怎么动。','所有力＋当前状态 → 下一刻运动','引擎计算重力、惯性、约束等，再更新状态；目标动作需要另外的控制器。']
];
const PARAMS={opensim:[['fmaxMultiplier','最大等长肌力 ×',.5,1.5,.1],['optimalFiberLengthMultiplier','最优纤维长度 ×',.9,1.1,.02],['tendonSlackLengthMultiplier','肌腱松弛长度 ×',.9,1.1,.02]],myohand:[['forceScale','原生肌力尺度 ×',.5,1.5,.1],['activationTimeScale','激活响应时间 ×',.5,2,.25]]};
const get=async(url,signal)=>{const r=await fetch(url,{signal});if(!r.ok)throw new Error(`数据暂不可用 (${r.status})`);return r.json();};
const safeFile=s=>typeof s==='string'&&/^[a-zA-Z0-9._-]+\.json$/.test(s);
const pretty=v=>JSON.stringify(v,null,2);

export function mountWorkbench(host,{engine='myohand',actionId=null}={}){
 let alive=true,index=null,model=null,run=null,baseline=null,frame=0,muscle=0,coordinate=0,lesson=0,playing=false,raf=0,last=0,time=0,stale=false,capabilities=null,job=null,selectedItem=null;
 const abort=new AbortController(),signal=abort.signal;
 const state={params:{},chartType:'activation',metric:'activation',chartTitle:'',baselineName:'基线'};let shouldPlay=false;
 const available=()=>!!capabilities?.engines?.[engine]?.available&&(!run||!capabilities.engines[engine].modelHash||capabilities.engines[engine].modelHash===run.manifest?.modelHash);
 host.classList.add('native-workbench');
 host.innerHTML=`<div class="nv-top"><div><h1>${engine==='opensim'?'OpenSim':'MyoHand'} · 原生实验</h1><span class="nv-status" role="status">加载模型与记录…</span></div><div class="nv-top-links"><a href="#${engine}/overview">原理详情</a><button class="nv-guide-toggle">${engine==='myohand'?'四步看懂':'求解步骤'}</button></div></div>
 <div class="nv-guide"></div>
 <div class="nv-grid"><section class="nv-stage"><div class="nv-view-label">当前参数</div><div class="nv-live-readout"></div><div class="nv-view-tools"><button class="nv-hand-view">手部</button><button class="nv-all-view">含前臂</button><button class="nv-wrap-toggle" aria-pressed="false" title="包绕：路径绕过模型中的障碍面。只显示当前肌肉实际参与包绕的对象。">包绕</button><button class="nv-marker-toggle" aria-pressed="false" hidden>标记拟合</button></div><div class="nv-scene"></div><div class="nv-scenes-note">原生路径 · 拖动旋转</div><div class="nv-scrub"><button class="nv-play" disabled>播放</button><select class="nv-speed" aria-label="仅改变回放速度，不改变求解时长"><option value="1">1× 回放</option><option value=".5">0.5× 回放</option><option value=".25">0.25× 回放</option></select><input class="nv-time" type="range" min="0" max="0" value="0" aria-label="原生记录时间"><output class="nv-time-label">0 s</output></div></section>
 <aside class="nv-controls"><label>动作 / 原生记录<select class="nv-runs" disabled></select></label><p class="nv-run-note"></p><div class="nv-counts"></div>
 <label>查看肌肉<select class="nv-muscle"></select></label><label>查看关节<select class="nv-coordinate"></select></label><div class="nv-quick" ${engine==='myohand'?'':'hidden'}><button class="nv-pulse" disabled>给一个短指令</button><button class="nv-tracking">想完成指定动作？</button></div><div class="nv-qc-summary"></div>
 <details class="nv-parameter-box" open><summary>改参数，看变化</summary><div class="nv-params"></div><div class="nv-buttons"><button class="nv-save" disabled>保存基线</button><button class="nv-reset" disabled>重置</button></div><div class="nv-baseline-note">尚未保存基线</div><button class="nv-solve" disabled>重新求解</button><button class="nv-cancel" hidden>取消求解</button><p class="nv-service-note">正在检查原生计算服务…</p></details>
 <div class="nv-request-editor"></div><div class="nv-buttons"><button class="nv-preset" disabled>导出参数</button><button class="nv-import">导入参数</button><input class="nv-import-file" type="file" accept="application/json,.json" hidden></div>
 <details class="nv-inspector-box"><summary>原生参数与依据</summary><input class="nv-inspector-search" placeholder="搜索原生字段 / 肌肉" aria-label="搜索原生参数"><div class="nv-inspector"></div><button class="nv-model-export">导出模型参数快照</button><p>可调字段见上方；其余字段只读。大数组见导出文件；当前模型不是个人生理真值。</p></details>
 <details><summary>动作覆盖与失败记录</summary><div class="nv-coverage">正在读取…</div></details>
 <details><summary>本次求解检查</summary><pre class="nv-qc"></pre></details></aside></div>
 <section class="nv-comparison" hidden><h2>原参数 / 当前参数</h2><p class="nv-diff"></p><div class="nv-pair"><div><span>基线</span><div class="nv-base-scene"></div></div><div><span>当前</span><div class="nv-current-scene"></div></div></div></section>
 <section class="nv-chart-section"><div class="nv-chart-toolbar"><h2>结果图表</h2><select class="nv-chart-type" aria-label="图表类型"><option value="activation">肌肉激活 · 全通道</option><option value="torque">各肌肉力矩贡献</option><option value="joint">关节力矩 · 随时间</option><option value="response">调参前后响应曲线</option></select><button class="nv-generate" disabled>生成图表</button></div>
 <div class="nv-chart" aria-live="polite"><p>请选择已有原生结果，或连接原生服务求解。</p></div><div class="nv-export"><button data-export="png" disabled>PNG 高清图</button><button data-export="svg" disabled>SVG 矢量图</button><button data-export="csv" disabled>CSV 数值</button><button data-export="json" disabled>JSON 记录</button></div><p class="nv-chart-note"></p></section>`;
 const $=s=>host.querySelector(s),status=s=>{if(alive)$('.nv-status').textContent=s;};
 $('.nv-baseline-note').insertAdjacentHTML('beforebegin','<label class="nv-name-label">快照名称<input class="nv-snapshot-name" maxlength="60" placeholder="例如：原参数 / 肌力增加"></label><button class="nv-read-existing" disabled>读取对应记录</button>');
 $('.nv-chart-type').insertAdjacentHTML('beforeend','<option value="balance">关节力矩 · 分项曲线</option><option value="sensitivity">参数变化 · 实际计算点</option>');
 $('.nv-chart-toolbar').insertAdjacentHTML('beforeend','<select class="nv-sensitivity-metric" aria-label="参数响应量" hidden><option value="activation">激活 a</option><option value="force">肌肉拉力 (N)</option><option value="angle">实际关节角 (°)</option><option value="reserve">辅助力矩 (N·m)</option></select><input class="nv-chart-title" maxlength="100" aria-label="自定义图标题" placeholder="图标题（可选）">');
 if(engine==='opensim')$('.nv-sensitivity-metric option[value="angle"]').textContent='规定关节角 · 输入 (°)';
 $('.nv-comparison').insertAdjacentHTML('afterbegin','<button class="nv-overlay-toggle" aria-pressed="false">同视角叠加</button>');
 $('.nv-parameter-box').insertAdjacentHTML('beforeend',parameterHelpHTML(engine));
 $('.nv-reset').textContent='撤销修改';$('.nv-reset').title='撤销尚未求解的参数修改，恢复当前计算记录的设置。';
 $('.nv-wrap-toggle').title=engine==='opensim'?'包绕：路径绕过模型中的障碍面。显示本帧全部肌肉实际使用的、已接入绘制的包绕对象。':'包绕：路径绕过模型中的障碍面。显示当前肌肉本帧实际使用的包绕对象。';
 let scene=null,baseScene=null,otherScene=null,currentSVG='',editor=null;
 function markStale(){stale=true;pause();status('参数已改 · 当前画面仍为上次结果');$('.nv-solve').disabled=!!job||!available();$('.nv-chart-note').textContent='新参数尚未求解；导出仍对应上次结果，不对应未求解参数。';}
 try{scene=new NativeScene({host:$('.nv-scene'),onSelect:item=>{const n=typeof item==='number'?item:item?.muscleIndex;if(Number.isInteger(n)){muscle=n;$('.nv-muscle').value=n;editor?.select(n);sync();draw();}}});}catch(e){$('.nv-scene').textContent='三维暂不可用；数值与图表仍可查看。';}
 function guide(){
  const g=$('.nv-guide');
  if(engine==='myohand'){g.innerHTML=`<div class="nv-steps">${LESSON.map((s,i)=>`<button data-lesson="${i}" ${i===lesson?'aria-current="step"':''}>${i+1}. ${s[0]}</button>`).join('')}</div><div class="nv-step-explanation"><strong>${LESSON[lesson][1]}</strong><span>${LESSON[lesson][2]}</span><details><summary>再深入一点</summary>${LESSON[lesson][3]} <a href="#myohand/${['control','activation','transmission','integration'][lesson]}">查看原理与官方依据 ↗</a></details></div>`;g.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lesson=+b.dataset.lesson;guide();state.chartType=lesson===2?'torque':lesson===1||lesson===3?'response':'activation';$('.nv-chart-type').value=state.chartType;draw();});}
  else g.innerHTML='<div class="nv-steps">'+[['scale','模型尺寸'],['ik','关节运动'],['id','力矩需求'],['so','肌肉分担']].map(([s,n],i)=>`<a href="#opensim/${s}">${i+1}. ${n}</a>`).join('')+'</div><p>下方是原生计算记录。实际执行与跳过的步骤，在“本次求解检查”中分别列出。</p>';
 }
 function renderParams(){const defs=index?.parameters?.length?index.parameters:PARAMS[engine].map(([key,label,min,max,step])=>({key,label,min,max,step,default:1}));
  $('.nv-params').innerHTML=defs.map(p=>`<label>${esc(p.label||p.key)}<span><input type="number" data-native-param="${esc(p.key)}" min="${p.min}" max="${p.max}" step="any" value="${state.params[p.key]??p.default??1}" aria-label="${esc(p.label||p.key)}"><small>${esc(p.unit||'倍')}</small></span></label>`).join('');
  $('.nv-params').querySelectorAll('input').forEach(input=>{input.title=PARAMETER_HELP[input.dataset.nativeParam]||'';input.oninput=()=>{state.params[input.dataset.nativeParam]=input.valueAsNumber;editor?.globalChange(state.params);markStale();};});
 }
 function setInspector(){if(!$('.nv-inspector-box').open)return;const q=$('.nv-inspector-search').value.toLowerCase(),lines=pretty({nativeModel:inspectorSummary(model),currentEffective:run?.manifest?.effective,requested:run?.manifest?.request,modelHash:run?.manifest?.modelHash,engineVersion:run?.manifest?.engineVersion,units:run?.manifest?.units}).split('\n');$('.nv-inspector').textContent=(q?lines.filter(x=>x.toLowerCase().includes(q)):lines).join('\n');}
 function setCoverage(){const coverage=index?.coverage||[],native=index?.nativeCoordinateCoverage||[];const labels={solved:'已计算',failed:'失败保留',unsupported:'模型不支持',mapped:'已映射',not_verified:'映射待验证',not_yet_verified:'尚待验证',TIMEOUT:'超时保留',timeout:'超时保留',not_run:'尚未运行',NOT_RUN:'尚未运行'};$('.nv-coverage').innerHTML=coverage.length?`<p>${coverage.length} 个原动作；映射与求解分开记录。</p>`+coverage.map(c=>`<div class="nv-coverage-row"><b>${esc(c.label||c.actionId||c.id)}</b><span>${esc(labels[c.status]||c.status)}${c.runStatus?' · '+esc(labels[c.runStatus]||c.runStatus):''}</span><small>${esc(c.reason||c.note||'')}${c.acceptedFrames!==undefined?` · 对账 ${c.acceptedFrames}/${c.attemptedFrames}`:''}</small></div>`).join(''):'尚未发布完整逐动作原生验收；不能把少量记录视作全部动作已完成。';if(native.length)$('.nv-coverage').innerHTML+=`<details><summary>另列：${native.length} 个原生坐标方向</summary><pre>${esc(pretty(native))}</pre></details>`;}
 function currentSensitivity(){const data=sensitivityData(run,baseline,engine,{frame,muscle,coordinate,metric:state.metric});if(engine==='opensim'&&state.metric==='angle'&&data.available)return {...data,metric:{...data.metric,label:'规定关节角（输入）'},note:data.note+' 此角度是逆分析的规定输入，不是肌肉参数变化后的运动响应。'};return data;}
 function draw(){if(!run?.frames?.length)return;const b=baseline&&sameChannels(run,baseline)?baseline:null;
  currentSVG=state.chartType==='balance'?jointBalanceChart(run,b,coordinate):state.chartType==='sensitivity'?sensitivityChart(currentSensitivity()):state.chartType==='torque'?torqueBars(run,b,frame,coordinate):state.chartType==='joint'?heatmap(run,'qfrcActuator_Nm',b):state.chartType==='response'?responseChart(run,b,muscle,coordinate):heatmap(run,'activation',b);
  if(state.chartType==='sensitivity'&&engine==='opensim'&&state.metric==='angle')currentSVG=currentSVG.replace('参数变化 → 响应','参数变化 → 规定角度（输入）');
  $('.nv-sensitivity-metric').hidden=state.chartType!=='sensitivity';
  if(state.chartTitle)currentSVG=currentSVG.replace(/(<text\b[^>]*>)[\s\S]*?(<\/text>)/,(m,start,end)=>start+esc(state.chartTitle)+end);
  $('.nv-chart').innerHTML=currentSVG;$('.nv-chart-note').textContent=stale?'显示与导出上次原生结果；待新参数求解后更新。':`数据：${run.manifest?.engine||engine} · ${run.muscleNames.length} 肌肉 · ${run.frames.length} 记录帧。${b?'基线与当前使用相同通道顺序。':''}`;
 }
function sync(){if(!run?.frames?.length)return;frame=Math.max(0,Math.min(frame,run.frames.length-1));const f=run.frames[frame];$('.nv-time').value=frame;$('.nv-time-label').textContent=format(f.time_s)+' s';scene?.setFrame(frame,muscle,coordinate);otherScene?.setFrame(frame,muscle,coordinate);if(baseScene&&baseline)baseScene.setFrame(frameAtTime(baseline,f.time_s),muscle,coordinate);$('.nv-live-readout').textContent=validFrame(f,run)?`${run.muscleNames[muscle]} · a ${format(f.activation?.[muscle])} · 拉力 ${format(f.tension_N?.[muscle]??f.force_N?.[muscle])} N\n${run.coordinateNames[coordinate]} · ${format(f.q?.[coordinate]*180/Math.PI)}° · ${format(f.torque_Nm?.[muscle]?.[coordinate])} N·m`:'本帧未通过求解检查 · 原始数值保留在导出记录中';if(engine==='myohand'){$('.nv-pulse').disabled=!!job||(!capabilities?.engines?.[engine]?.available&&(effectiveRequest(run,engine).mode!=='pulse'||run.muscleNames[muscle]!==effectiveRequest(run,engine).muscle));$('.nv-pulse').textContent=capabilities?.engines?.[engine]?.available?'给一个短指令':'播放已有短指令';}if(state.chartType==='torque'||state.chartType==='sensitivity')draw();}
 function pause(){playing=false;cancelAnimationFrame(raf);$('.nv-play').textContent='播放';}
 function tick(now){if(!alive||!playing||!run)return;time+=Math.min(.1,(now-last)/1000)*Number($('.nv-speed').value);last=now;frame=frameAtTime(run,time);sync();if(time>=run.frames.at(-1).time_s){pause();return;}raf=requestAnimationFrame(tick);}
 function comparison(){baseScene?.dispose();otherScene?.dispose();baseScene=null;otherScene=null;const show=baseline&&run&&sameChannels(baseline,run);$('.nv-comparison').hidden=!show;if(!show)return;
  const manifest=comparisonManifest(baseline,run,engine,{baselineName:state.baselineName,currentName:$('.nv-snapshot-name').value||'当前'});
  $('.nv-diff').textContent=manifest?`${manifest.protocol}。${state.baselineName} → ${manifest.current.name}：`+(manifest.changes.length?manifest.changes.map(c=>`${c.label} ${c.before} → ${c.after} ${c.unit}`).join('；'):'参数相同'):'无法确认相同实验条件。';
  try{baseScene=new NativeScene({host:$('.nv-base-scene')});otherScene=new NativeScene({host:$('.nv-current-scene')});for(const s of [baseScene,otherScene])if(model)s.setModel?.(model);baseScene.setRun(baseline);otherScene.setRun(run);let syncing=false;const lock=(a,b)=>{if(syncing)return;syncing=true;b.setCameraState(a.getCameraState());syncing=false;};baseScene.onCameraChangeSubscribe?.(()=>lock(baseScene,otherScene));otherScene.onCameraChangeSubscribe?.(()=>lock(otherScene,baseScene));}catch{}if($('.nv-overlay-toggle').getAttribute('aria-pressed')==='true')otherScene?.setOverlayRun?.(baseline);sync();
 }
 function acceptRun(data,item){if(!Array.isArray(data.frames)||!data.frames.length||!Array.isArray(data.muscleNames))throw new Error('原生记录没有可显示的完整帧');verifyNativeBinding(model,data);const firstLoad=!run;run=data;selectedItem=item;frame=0;time=run.frames[0].time_s;const request=effectiveRequest(run,engine);muscle=Math.max(0,run.muscleNames.indexOf(request.muscle||run.muscleNames[muscle]));coordinate=Math.max(0,run.coordinateNames.indexOf(request.coordinate||run.coordinateNames[coordinate]));stale=false;state.params=parameterValues(run,engine,index.parameters||[]);
  if(firstLoad&&engine==='opensim'&&!request.muscle){const scores=run.muscleNames.map((_,i)=>Math.max(0,...run.frames.filter(f=>validFrame(f,run)).map(f=>Math.abs(f.torque_Nm?.[i]?.[coordinate]||0))));if(Math.max(...scores)>0)muscle=scores.indexOf(Math.max(...scores));$('.nv-muscle').title='首次高亮：所选关节在有效记录帧中峰值绝对力矩最大的肌肉；全部肌肉仍可选择。';}
  if(baseline&&!matchingExperiment(baseline,run,engine)){baseline=null;$('.nv-baseline-note').textContent='动作或输入条件不同，已退出调参比较；请重新保存基线。';}
  $('.nv-muscle').innerHTML=run.muscleNames.map((n,i)=>`<option value="${i}">${i+1}. ${esc(n)}</option>`).join('');$('.nv-coordinate').innerHTML=run.coordinateNames.map((n,i)=>`<option value="${i}">${esc(n)}</option>`).join('');$('.nv-muscle').value=muscle;$('.nv-coordinate').value=coordinate;
  $('.nv-counts').textContent=`${engine==='opensim'?'当前左手模型':'原生右手模型'} · ${run.muscleNames.length} 肌肉 · ${run.coordinateNames.length} 坐标`;
  $('.nv-run-note').textContent=(item?.label||run.manifest?.label||'原生计算')+' · '+({solved:'原生已计算',partial:'含未通过检查的帧',failed:'求解失败'}[run.manifest?.status]||run.manifest?.status||'已记录');
  $('.nv-time').max=run.frames.length-1;$('.nv-qc').textContent=pretty({status:run.manifest?.status,qc:run.manifest?.qc||run.checks,stages:run.manifest?.stages,limitations:run.manifest?.limitations});
  const qc=run.manifest?.qc||{};$('.nv-qc-summary').textContent=engine==='opensim'?`力矩对账 ${qc.acceptedFrames??'—'}/${run.frames.length} 帧；不等于低 reserve 或全部约束通过。Scale / IK：此记录请见步骤检查。`:`${request.mode==='tracking'?`动作跟踪${qc.trackingAccepted?'通过':'未通过'} · 选中关节 RMS ${format(qc.trackingRmsSelected_deg)}°。`:'短指令实验 · 不要求跟随目标动作。'} 关节限位最大超出 ${format((qc.nativeJointLimitMaxViolation_rad||0)*180/Math.PI)}°。`;
  editor=createRequestEditor($('.nv-request-editor'),{engine,model,getRun:()=>run,onChange:markStale});editor.reset(run);editor.select(muscle);
  if(qc.numericPassed===false)$('.nv-qc-summary').textContent='本次原生数值检查失败；画面与曲线不显示为有效结果，原始数据保留在导出记录中。';
  $('.nv-marker-toggle').hidden=!run.frames.some(f=>f.observedMarkers_m?.length);$('.nv-marker-toggle').setAttribute('aria-pressed','false');scene?.setMarkersVisible?.(false);
  for(const s of [scene]){if(model)s?.setModel?.(model);s?.setRun(run);}renderParams();setInspector();comparison();sync();draw();
  host.querySelectorAll('.nv-save,.nv-reset,.nv-play,.nv-preset,.nv-generate,.nv-read-existing,[data-export]').forEach(b=>b.disabled=false);$('.nv-solve').disabled=!available();if(capabilities?.engines?.[engine]?.available&&!available())$('.nv-service-note').textContent='这份记录使用另一套缩放模型；当前本地服务只连接基准模型，不能直接重算。';else $('.nv-service-note').textContent=available()?'本地原生服务已连接：修改参数后可重新计算。':'线上尚无原生计算服务；可选择已有参数记录对比。任意调参需本地原生服务。';status('原生结果已加载 · '+(available()?'本地可重新求解':'当前为原生结果回放'));if(shouldPlay){shouldPlay=false;$('.nv-play').click();}
 }
 let loadVersion=0;
 const models=new Map();
 async function loadModel(item){if(item.memoryModel)return item.memoryModel;const mf=item.modelFile||index.modelFile,gf=item.geometryFile||index.geometryFile,key=mf+'|'+gf;if(models.has(key))return models.get(key);let m=null;if(safeFile(mf)){m=await get(DATA+mf,signal);if(safeFile(gf)){const g=await get(DATA+gf,signal),mi=m.manifest||m,gi=g.manifest||g;if(mi.modelId!==gi.modelId||mi.modelHash!==gi.modelHash)throw new Error('模型与几何哈希不匹配，已阻止混用');m={...m,...g};}models.set(key,m);}return m;}
 async function loadRun(i){pause();const v=++loadVersion,item=index.runs[i];if(!item||(!item.memoryRun&&!safeFile(item.file)))return;status('读取原生结果…');try{const [data,nativeModel]=await Promise.all([item.memoryRun||get(DATA+item.file,signal),loadModel(item)]);if(alive&&v===loadVersion){model=nativeModel;acceptRun(data,item);}}catch(e){if(alive){status(e.message+(run?'；仍显示上次成功载入的记录':''));if(selectedItem)$('.nv-runs').value=index.runs.indexOf(selectedItem);}}}
 $('.nv-runs').onchange=()=>loadRun(+$('.nv-runs').value);
 $('.nv-guide-toggle').onclick=()=>{$('.nv-guide').hidden=!$('.nv-guide').hidden;};
 $('.nv-inspector-search').oninput=setInspector;
 $('.nv-inspector-box').ontoggle=setInspector;$('.nv-model-export').onclick=()=>downloadFile(engine+'-model-parameters.json',pretty({nativeModel:model,currentEffective:run?.manifest?.effective,units:run?.manifest?.units}));
 $('.nv-muscle').onchange=()=>{muscle=+$('.nv-muscle').value;editor?.select(muscle);sync();draw();};$('.nv-coordinate').onchange=()=>{coordinate=+$('.nv-coordinate').value;sync();draw();};
 $('.nv-hand-view').onclick=()=>scene?.setView('hand');$('.nv-all-view').onclick=()=>scene?.setView('all');$('.nv-wrap-toggle').onclick=()=>{const b=$('.nv-wrap-toggle'),show=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',show);scene?.setWrappingVisible(show);};
 $('.nv-marker-toggle').onclick=()=>{const b=$('.nv-marker-toggle'),show=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',show);scene?.setMarkersVisible?.(show);};
 $('.nv-pulse').onclick=()=>{if(!run)return;if(capabilities?.engines?.[engine]?.available){editor.pulse(run.muscleNames[muscle]);shouldPlay=true;$('.nv-solve').click();}else $('.nv-play').click();};
 $('.nv-tracking').onclick=()=>{const i=index?.runs?.findIndex(r=>r.mode==='tracking'||/track|tuned/.test(r.file));if(i>=0){$('.nv-runs').value=i;loadRun(i);lesson=3;guide();state.chartType='response';$('.nv-chart-type').value='response';}};
 $('.nv-time').oninput=()=>{pause();frame=+$('.nv-time').value;time=run.frames[frame].time_s;sync();};
 $('.nv-play').onclick=()=>{if(playing){pause();return;}if(frame>=run.frames.length-1){frame=0;time=run.frames[0].time_s;}playing=true;last=performance.now();$('.nv-play').textContent='暂停';raf=requestAnimationFrame(tick);};
 $('.nv-save').onclick=()=>{baseline=run;state.baselineName=$('.nv-snapshot-name').value.trim()||selectedItem?.label||'基线';$('.nv-baseline-note').textContent='已保存：'+state.baselineName;comparison();draw();};
 $('.nv-overlay-toggle').onclick=()=>{const b=$('.nv-overlay-toggle'),on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',on);otherScene?.setOverlayRun?.(on?baseline:null);};
 $('.nv-read-existing').onclick=async()=>{if(!run||job)return;const anchor=run,request=editor?.values()||effectiveRequest(run,engine);$('.nv-read-existing').disabled=true;status('查找完全匹配的已有原生记录…');try{for(const item of index.runs.filter(x=>x.actionId===(request.actionId||selectedItem?.actionId))){const candidate=item.memoryRun||await get(DATA+item.file,signal);if(!alive||run!==anchor)return;if(matchingRequestedParameters(candidate,anchor,engine,request)){model=await loadModel(item);acceptRun(candidate,item);$('.nv-runs').value=index.runs.indexOf(item);return;}}status('没有完全匹配的已有结果；需连接原生服务重算，不进行插值。');}catch(e){if(alive)status(e.message);}finally{if(alive)$('.nv-read-existing').disabled=false;}};
 $('.nv-reset').onclick=()=>{state.params=parameterValues(run,engine,index.parameters||[]);stale=false;editor?.reset(run);editor?.select(muscle);renderParams();status('已恢复当前运行参数');draw();};
 $('.nv-chart-type').onchange=()=>{state.chartType=$('.nv-chart-type').value;draw();};$('.nv-generate').onclick=()=>{draw();$('.nv-chart').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
 $('.nv-sensitivity-metric').onchange=()=>{state.metric=$('.nv-sensitivity-metric').value;draw();};$('.nv-chart-title').oninput=()=>{state.chartTitle=$('.nv-chart-title').value.trim();draw();};
 $('.nv-preset').onclick=()=>downloadFile(`${engine}-parameters.json`,pretty({schemaVersion:1,engine,modelId:run.manifest?.modelId,modelHash:run.manifest?.modelHash,request:editor?.values()||effectiveRequest(run,engine),parameters:state.params,units:run.manifest?.units,pending:stale}));
 $('.nv-import').onclick=()=>$('.nv-import-file').click();$('.nv-import-file').onchange=async()=>{try{const file=$('.nv-import-file').files[0];if(!file||file.size>100000||!run)throw new Error('参数文件过大、为空或尚未加载模型');const defs=index.parameters||PARAMS[engine].map(([key,label,min,max])=>({key,label,min,max})),p=validatePreset(JSON.parse(await file.text()),run,engine,defs);state.params={...parameterValues(run,engine,defs),...p.parameters};editor?.import(p.request||effectiveRequest(run,engine));editor?.globalChange(state.params);stale=true;renderParams();status('已导入参数 · 待求解');}catch(e){status(e.message);}finally{$('.nv-import-file').value='';}};
 host.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{if(!run)return;const name=`${engine}-${state.chartType}`,sensitivity=state.chartType==='sensitivity'?currentSensitivity():null;try{if(b.dataset.export==='png')await downloadPNG(name+'.png',currentSVG);if(b.dataset.export==='svg')downloadFile(name+'.svg',currentSVG,'image/svg+xml');if(b.dataset.export==='csv')downloadFile(name+'.csv',sensitivity?sensitivityCSV(sensitivity):chartCSV(run,baseline),'text/csv;charset=utf-8');if(b.dataset.export==='json')downloadFile(name+'.json',pretty({schemaVersion:1,current:run,baseline,comparison:comparisonManifest(baseline,run,engine,{baselineName:state.baselineName,currentName:$('.nv-snapshot-name').value||'当前'}),sensitivity,selection:{frame,muscle,coordinate,chart:state.chartType,title:state.chartTitle},pendingParameters:stale?state.params:null,pendingRequest:stale?editor?.values():null}));status('已导出 '+b.dataset.export.toUpperCase());}catch(e){status(e.message);}});
 $('.nv-solve').onclick=async()=>{if(!available()||!run||job)return;const inputs=[...host.querySelectorAll('[data-native-param]')];if(inputs.some(i=>!i.checkValidity()||!Number.isFinite(i.valueAsNumber))||!editor?.valid()){status('请使用标注范围内的有效参数');return;}pause();$('.nv-solve').disabled=true;$('.nv-cancel').hidden=false;const lock=[...host.querySelectorAll('.nv-controls input,.nv-controls select,.nv-controls button:not(.nv-cancel)')];lock.forEach(i=>i.disabled=true);
  try{const previous=editor?.values()||effectiveRequest(run,engine),request=engine==='myohand'?{...previous,...state.params}:{...previous,parameters:{...(previous.parameters||{}),...state.params}};delete request.runId;const response=await fetch('/api/native/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({engine,modelHash:run.manifest?.modelHash,request}),signal});const submitted=await response.json();if(!response.ok)throw new Error(submitted.error||'求解请求失败');job=submitted.id;
   while(alive&&job){const j=await get('/api/native/jobs/'+job,signal);status(j.stage||j.status);if(j.status==='complete'){job=null;const item={label:($('.nv-snapshot-name').value.trim()||'本次原生求解')+' · 本会话',actionId:request.actionId,memoryRun:j.result,memoryModel:model,parameters:{...state.params}};verifyNativeBinding(model,j.result);index.runs.push(item);$('.nv-runs').insertAdjacentHTML('beforeend',`<option value="${index.runs.length-1}">${esc(item.label)}</option>`);$('.nv-runs').value=index.runs.length-1;acceptRun(j.result,item);break;}if(['failed','cancelled'].includes(j.status))throw new Error(j.error||j.status);await new Promise(resolve=>setTimeout(resolve,1000));}
  }catch(e){shouldPlay=false;if(alive)status(e.message);}finally{job=null;if(alive){lock.forEach(i=>i.disabled=false);$('.nv-cancel').hidden=true;$('.nv-solve').disabled=!available();sync();}}
 };
 $('.nv-cancel').onclick=async()=>{if(job)await fetch('/api/native/jobs/'+job,{method:'DELETE'});};
 guide();
 Promise.allSettled([get(DATA+engine+'-index.json',signal),get('/api/native/capabilities',signal)]).then(async result=>{if(!alive)return;const [data,service]=result;capabilities=service.status==='fulfilled'?service.value:null;const online=capabilities?.engines?.[engine]?.available;$('.nv-solve').disabled=!online;$('.nv-service-note').textContent=online?'本地原生服务已连接：修改参数后可重新计算。':'线上尚无原生计算服务；可选择已有参数记录对比。任意调参需本地原生服务。';
  if(data.status!=='fulfilled'){status('原生记录尚未发布');$('.nv-run-note').textContent='此分支尚未具备可展示的原生结果；不以教学计算替代。';return;}index=data.value;index.runs=index.runs||index.items||[];$('.nv-runs').innerHTML=index.runs.map((r,i)=>`<option value="${i}">${esc(r.label||r.file)}</option>`).join('');$('.nv-runs').disabled=!index.runs.length;setCoverage();
  if(safeFile(index.coverageFile)&&!index.nativeCoordinateCoverage)try{const ledger=await get(DATA+index.coverageFile,signal);index.nativeCoordinateCoverage=ledger.nativeCoordinateActions||[];if(alive)setCoverage();}catch{}if(!alive)return;const i=actionId?index.runs.findIndex(r=>r.actionId===actionId):0;
  if(actionId&&i<0){status('该原动作暂无对应原生结果');const row=index.coverage?.find(c=>c.actionId===actionId);$('.nv-run-note').textContent=(row?.label||actionId)+'：'+(row?.reason||'尚未形成已验证记录。');const suggestions=index.runs.map((r,n)=>({r,n})).filter(({r})=>row?.coordinate&&r.actionId?.startsWith('native')&&r.actionId.includes(':'+row.coordinate+':'));if(suggestions.length){const box=document.createElement('div');box.className='nv-quick';box.innerHTML='<p>可另看此关节的新原生示例（不是原片段）：</p>'+suggestions.map(({r,n})=>`<button data-alternative="${n}">${esc(r.label)}</button>`).join('');$('.nv-run-note').after(box);box.querySelectorAll('button').forEach(b=>b.onclick=()=>{$('.nv-runs').value=b.dataset.alternative;loadRun(+b.dataset.alternative);box.remove();});}setInspector();renderParams();return;}$('.nv-runs').value=Math.max(0,i);if(index.runs.length)loadRun(Math.max(0,i));
 });
 return {dispose(){alive=false;abort.abort();cancelAnimationFrame(raf);if(job)fetch('/api/native/jobs/'+job,{method:'DELETE'}).catch(()=>{});scene?.dispose();baseScene?.dispose();otherScene?.dispose();host.classList.remove('native-workbench');host.innerHTML='';},snapshot:()=>({engine,loaded:!!run,frame,stale,baseline:!!baseline,modelId:run?.manifest?.modelId})};
}
