import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.TEST_URL||'http://127.0.0.1:4180',out=process.env.QA_OUT||'test-output/native-v2-edge';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});
const checks=[],check=(name,condition)=>{assert.ok(condition,name);checks.push(name);};
try{
 const page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#myohand/native');await page.locator('.nv-chart svg').waitFor();
 check('reduced motion does not autoplay',await page.locator('.nv-play').innerText()==='播放');
 check('offline service disables recompute',await page.locator('.nv-solve').isDisabled());
 await page.locator('.nv-save').click();await page.locator('[data-native-param="forceScale"]').fill('1.25');await page.locator('.nv-read-existing').click();await page.waitForFunction(()=>document.querySelector('.nv-status')?.textContent.includes('原生结果已加载'));
 check('offline exact existing result loaded',await page.locator('.nv-run-note').innerText().then(x=>x.includes('1.25')));
 check('baseline comparison retained',await page.locator('.nv-comparison').isVisible());
 await page.locator('.nv-overlay-toggle').click();await page.locator('.nv-chart-type').selectOption('sensitivity');await page.locator('.nv-sensitivity-metric').selectOption('force');
 check('sensitivity renders real sampled scale',await page.locator('.nv-chart svg').textContent().then(x=>x.includes('1.25')&&x.includes('两个真实计算点')));
 await page.screenshot({path:out+'/offline-comparison.png',fullPage:true});
 await page.locator('[data-native-param="forceScale"]').fill('1.234');await page.locator('.nv-read-existing').click();await page.waitForFunction(()=>document.querySelector('.nv-status')?.textContent.includes('没有完全匹配'));
 check('no interpolated fake result',await page.locator('.nv-run-note').innerText().then(x=>x.includes('1.25')));
 await page.route('**/myohand-index.json',route=>route.fulfill({json:{runs:[]}}));await page.reload();await page.waitForFunction(()=>document.querySelector('.nv-coverage')?.textContent.includes('尚未发布'));
 check('empty results cannot play or solve',await page.locator('.nv-play').isDisabled()&&await page.locator('.nv-solve').isDisabled());
 await page.unroute('**/myohand-index.json');await page.route('**/myohand-model.json',route=>route.fulfill({status:404,body:'missing'}));await page.reload();await page.waitForFunction(()=>document.querySelector('.nv-status')?.textContent.includes('404'));
 check('missing asset does not fabricate geometry',await page.locator('.nv-play').isDisabled());
 await page.unroute('**/myohand-model.json');await page.route('**/myohand-run-pulse.json',async route=>{const response=await route.fetch(),r=await response.json();r.manifest.qc.numericPassed=false;await route.fulfill({json:r});});await page.reload();await page.locator('.nv-chart svg').waitFor();
 check('numeric failure explicitly marked',await page.locator('.nv-qc-summary').textContent().then(x=>x.includes('数值检查失败')));
 check('numeric failure masks readout',await page.locator('.nv-live-readout').textContent().then(x=>x.includes('未通过')));
 check('numeric failure retains grey chart',await page.locator('.nv-chart svg rect[fill="#b8bcc1"]').count()>0);
 await page.unroute('**/myohand-run-pulse.json');await page.close();
 const fallback=await browser.newPage();fallback.on('pageerror',e=>errors.push(e.message));
 await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return /webgl/i.test(type)?null:original.call(this,type,...args);};});
 await fallback.goto(base+'/#myohand/native');await fallback.locator('.nv-chart svg').waitFor();
 check('WebGL failure retains numeric charts',await fallback.locator('.nv-muscle option').count()===39);
 check('WebGL limitation visible',await fallback.locator('.nv-scene').textContent().then(x=>x.includes('WebGL')));
 await fallback.goto(base+'/#mano/shape');check('MANO survives WebGL failure',await fallback.locator('.mano-steps button').count()===4);
 check('no uncaught errors',errors.length===0);
 await fs.writeFile(out+'/RESULTS.json',JSON.stringify({base,checks,errors,at:new Date().toISOString()},null,2));console.log(JSON.stringify({checks:checks.length,errors}));
}finally{await browser.close();}
